kernel install fixes

diff --git a/systemd/99-uki-uefi-setup.install b/systemd/99-uki-uefi-setup.install
--- a/systemd/99-uki-uefi-setup.install
+++ b/systemd/99-uki-uefi-setup.install
@@ -25,12 +25,9 @@ UKI_FILE_ESP="$UKI_DIR_ESP/$ENTRY_TOKEN-$KERNEL_VERSION.efi"
 
 case "$COMMAND" in
     remove)
-        # 'tries' file may had changed after UKI got installed, remove
-        # all $UKI_DIR_ESP/$ENTRY_TOKEN-$KERNEL_VERSION{,\+.*}.efi entries.
         [ "$KERNEL_INSTALL_VERBOSE" -gt 0 ] && \
-            echo "Removing $UKI_DIR_ESP/$ENTRY_TOKEN-$KERNEL_VERSION*.efi from UEFI boot entries"
-        for uki in "$UKI_DIR_ESP/$ENTRY_TOKEN-$KERNEL_VERSION.efi" \
-            "$UKI_DIR_ESP/$ENTRY_TOKEN-$KERNEL_VERSION+"*".efi"; do
+            echo "Removing $UKI_DIR_ESP/$ENTRY_TOKEN-$KERNEL_VERSION.efi from UEFI boot entries"
+        for uki in "$UKI_DIR_ESP/$ENTRY_TOKEN-$KERNEL_VERSION.efi"; do
             [ -f "$uki" ] && kernel-bootcfg --remove-uki "$uki"
         done
         ;;
@@ -48,8 +45,8 @@ case "$COMMAND" in
 
         # Copy the UKI to the ESP when $BOOT and ESP differ
         if [ ! -f "$UKI_FILE_ESP" ]; then
-            install -D -m 0644 "$KERNEL_IMAGE" "$UKI_FILE_ESP" || {
-                echo "Error: could not copy '$KERNEL_IMAGE' to '$UKI_FILE_ESP'." >&2
+            install -D -m 0644 "$UKI_FILE_BOOT" "$UKI_FILE_ESP" || {
+                echo "Error: could not copy '$UKI_FILE_BOOT' to '$UKI_FILE_ESP'." >&2
 	        exit 1
             }
         fi
